"""Tests for the deployment preflight checks.

The two conditions covered here are the ones that took the stack down on
2026-08-24 and were each diagnosed far from their cause: containers created
while the host advertised only a loopback resolver, and a `snp-scout` image
older than the checkout it is supposed to be running.

Everything asserted here is a pure function of text the checks read, so the
suite never needs Docker.
"""

from __future__ import annotations

import pytest

from scripts.preflight_stack import (
    classify_image_revision,
    classify_resolv_conf,
    collect_findings,
    exit_code_for,
)

# The exact file a broken container carried, verbatim.
BROKEN_RESOLV = """\
# Generated by Docker Engine.
# This file can be edited; Docker Engine will not make further changes once it
# has been modified.

nameserver 127.0.0.11
options ndots:0

# Based on host file: '/etc/resolv.conf' (internal resolver)
# NO EXTERNAL NAMESERVERS DEFINED
# Overrides: []
# Option ndots from: internal
"""

# The same container after `--force-recreate`, verbatim.
HEALTHY_RESOLV = """\
# Generated by Docker Engine.
nameserver 127.0.0.11
options ndots:0

# Based on host file: '/etc/resolv.conf' (internal resolver)
# ExtServers: [host(192.168.2.253) host(192.168.2.235)]
# Overrides: []
"""


def test_no_external_nameservers_is_reported_with_a_remedy() -> None:
    finding = classify_resolv_conf(BROKEN_RESOLV)
    assert not finding.ok
    assert "NO EXTERNAL NAMESERVERS" in finding.detail
    assert "--force-recreate" in finding.remedy


def test_external_servers_present_is_healthy() -> None:
    finding = classify_resolv_conf(HEALTHY_RESOLV)
    assert finding.ok
    assert "192.168.2.253" in finding.detail


def test_a_plain_external_nameserver_is_healthy() -> None:
    """A container on the default bridge copies the host file as-is."""
    finding = classify_resolv_conf("nameserver 10.0.0.53\n")
    assert finding.ok


def test_only_a_loopback_nameserver_is_not_healthy() -> None:
    """127.0.0.11 alone proves nothing: it is Docker's own resolver."""
    finding = classify_resolv_conf("nameserver 127.0.0.11\noptions ndots:0\n")
    assert not finding.ok


def test_empty_resolv_conf_is_not_silently_passed() -> None:
    finding = classify_resolv_conf("")
    assert not finding.ok


def test_matching_revision_is_healthy() -> None:
    finding = classify_image_revision(
        image_revision="2d2b9dd4d0cc2c9ca9341f48afbac053002bf762",
        head_revision="2d2b9dd4d0cc2c9ca9341f48afbac053002bf762",
        image_created="2026-08-24T10:00:00+07:00",
        head_committed="2026-08-24T09:00:00+07:00",
    )
    assert finding.ok


def test_revision_mismatch_is_drift() -> None:
    finding = classify_image_revision(
        image_revision="268af30aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        head_revision="2d2b9dd4d0cc2c9ca9341f48afbac053002bf762",
        image_created="2026-08-24T10:00:00+07:00",
        head_committed="2026-08-24T09:00:00+07:00",
    )
    assert not finding.ok
    assert "268af30" in finding.detail
    assert "docker compose build scout" in finding.remedy


def test_unlabelled_image_older_than_head_is_drift() -> None:
    """The exact 2026-08-24 case: no label, image built before the fix landed."""
    finding = classify_image_revision(
        image_revision=None,
        head_revision="2d2b9dd4d0cc2c9ca9341f48afbac053002bf762",
        image_created="2026-08-20T09:57:00+07:00",
        head_committed="2026-08-21T14:48:31+07:00",
    )
    assert not finding.ok
    assert "docker compose build scout" in finding.remedy


def test_unlabelled_image_newer_than_head_is_reported_as_unverifiable() -> None:
    """A newer timestamp is not proof: the tree may have uncommitted changes."""
    finding = classify_image_revision(
        image_revision=None,
        head_revision="2d2b9dd4d0cc2c9ca9341f48afbac053002bf762",
        image_created="2026-08-24T10:00:00+07:00",
        head_committed="2026-08-21T14:48:31+07:00",
    )
    assert not finding.ok
    assert "no revision label" in finding.detail


def test_timezones_are_compared_correctly() -> None:
    """+07:00 09:57 is AFTER 01:00Z, and a naive string compare gets this wrong."""
    finding = classify_image_revision(
        image_revision=None,
        head_revision="deadbeef",
        image_created="2026-08-20T09:57:00+07:00",
        head_committed="2026-08-20T01:00:00+00:00",
    )
    # Image is genuinely newer than HEAD here; still unverifiable, never "drift".
    assert "no revision label" in finding.detail


def test_exit_code_is_the_project_contract() -> None:
    from scripts.preflight_stack import Finding

    ok = Finding(check="c", ok=True, detail="", remedy="")
    bad = Finding(check="c", ok=False, detail="", remedy="")
    assert exit_code_for([ok, ok]) == 0
    assert exit_code_for([ok, bad]) == 1
    assert exit_code_for([]) == 2


def test_an_unreadable_check_never_reports_a_clean_run() -> None:
    """A stopped container must not read as a pass.

    Skipping a check it could not run and then exiting `0` is the failure mode
    this whole script exists to prevent: an absent signal presented as a good
    one. Unreadable is infrastructure (`2`), not a finding (`1`).
    """
    from scripts.preflight_stack import Finding

    ok = Finding(check="c", ok=True, detail="", remedy="")
    unavailable = Finding(
        check="container-dns", ok=False, detail="service not running", available=False
    )
    assert exit_code_for([ok, unavailable]) == 2
    assert exit_code_for([unavailable]) == 2


def test_live_preflight_reads_the_explicit_compose_project(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    commands: list[list[str]] = []

    def fake_run(command: list[str]) -> str:
        commands.append(command)
        if command[-1] == "/etc/resolv.conf":
            return HEALTHY_RESOLV
        if command[:3] == ["docker", "image", "inspect"]:
            return "2026-08-26T10:00:00+00:00|" + "a" * 40
        if command[:3] == ["git", "rev-parse", "HEAD"]:
            return "a" * 40
        return "2026-08-26T09:00:00+00:00"

    monkeypatch.setattr("scripts.preflight_stack._run", fake_run)

    findings = collect_findings(compose_project="snp-v021-staging")

    assert all(finding.ok for finding in findings)
    assert commands[0][:5] == [
        "docker",
        "compose",
        "--project-name",
        "snp-v021-staging",
        "exec",
    ]


def test_live_preflight_preserves_the_selected_overlay_files(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    commands: list[list[str]] = []

    def fake_run(command: list[str]) -> str:
        commands.append(command)
        if command[-1] == "/etc/resolv.conf":
            return HEALTHY_RESOLV
        if command[:3] == ["docker", "image", "inspect"]:
            return "2026-08-26T10:00:00+00:00|" + "a" * 40
        if command[:3] == ["git", "rev-parse", "HEAD"]:
            return "a" * 40
        return "2026-08-26T09:00:00+00:00"

    monkeypatch.setattr("scripts.preflight_stack._run", fake_run)

    collect_findings(
        compose_project="snp-v021-staging",
        compose_files=("docker-compose.yml", "docker-compose.staging.yml"),
    )

    assert commands[0][:9] == [
        "docker",
        "compose",
        "--project-name",
        "snp-v021-staging",
        "--file",
        "docker-compose.yml",
        "--file",
        "docker-compose.staging.yml",
        "exec",
    ]


def test_staging_revision_remedy_rebuilds_the_selected_unique_image() -> None:
    finding = classify_image_revision(
        image_revision="b" * 40,
        head_revision="a" * 40,
        image_created="2026-08-26T10:00:00+00:00",
        head_committed="2026-08-26T09:00:00+00:00",
        compose_project="snp-v021-staging",
        image="snp-v021-scout:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        compose_files=("docker-compose.yml", "docker-compose.staging.yml"),
    )

    assert (
        "--project-name snp-v021-staging --file docker-compose.yml --file "
        "docker-compose.staging.yml build scout"
    ) in finding.remedy
    assert (
        "SNP_SCOUT_IMAGE=snp-v021-scout:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        in (finding.remedy)
    )
