-- Intentionally contains no schema objects.
--
-- `scripts/migrate_postgres.py` and `config/postgres/migrations/*.sql` are the
-- single schema path for both fresh installations and upgrades.  Keeping this
-- compatibility file prevents old deployment references from silently
-- recreating a second, divergent schema.
