#!/usr/bin/env python3
"""gen_index.py — deterministic index.md generator + vault linter.

Serves R-1.3 and R-6.5 (design.md §5). Two jobs, kept distinct:

  1. GENERATE  wiki/index.md by gathering every page's `summary`. The
     output is deterministic (stable sort) so it always matches the page
     set — regenerating after a merge can never drift (R-6.5).

  2. LINT the vault at the "does it exist on disk / is it well-formed"
     layer:
        · required frontmatter fields present (R-1.3)
        · sources[] element shape + `path` exists on disk (R-1.4)
        · no forbidden `related:` field — [[wikilink]] is the only link
          source (R-1.5)
        · wikilinks resolve to a real page
        · orphan pages (no inbound wikilink from any other page)

     This is a DIFFERENT layer from verify_addresses.py (T-2.5), which
     asks whether a `hint` actually retrieves its file from RAG's KG.
     gen_index.py checks the filesystem; verify_addresses.py checks RAG.
     Do not merge them (design.md §5).

Exit code is nonzero when lint finds errors, so this can gate a merge.

Usage:
    python scripts/gen_index.py            # lint + rewrite wiki/index.md
    python scripts/gen_index.py --check    # lint + verify index is current
                                           #   (writes nothing; CI mode)
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
WIKI_DIR = REPO_ROOT / "wiki"
INDEX_PATH = WIKI_DIR / "index.md"

sys.path.insert(0, str(REPO_ROOT))
from scout import vault  # noqa: E402

GENERATED_HEADER = "<!-- GENERATED FILE — DO NOT EDIT BY HAND -->"

# Display order for the type sections in index.md. Deterministic.
TYPE_ORDER = ["technique", "playbook", "concept", "entity"]
TYPE_HEADING = {
    "technique": "Techniques",
    "playbook": "Playbooks",
    "concept": "Concepts",
    "entity": "Entities",
}


def collect_lint(pages: list[vault.Page]) -> vault.LintResult:
    """Run the full vault lint: tree + per-page + orphan detection."""
    result = vault.LintResult()

    tree = vault.check_tree(WIKI_DIR)
    result.errors.extend(tree.errors)

    slugs = {p.slug for p in pages}
    for page in pages:
        r = vault.lint_page(page, known_slugs=slugs)
        result.errors.extend(r.errors)
        result.warnings.extend(r.warnings)

    # Orphan detection: a page with no inbound wikilink from any other
    # page. index/archive/log are navigational, never "orphans".
    NAVIGATIONAL = {"index", "archive", "log"}
    inbound: dict[str, int] = defaultdict(int)
    for page in pages:
        for link in page.wikilinks:
            target = link.split("|")[0].split("#")[0].strip()
            if target != page.slug:
                inbound[target] += 1
    for page in pages:
        if page.slug in NAVIGATIONAL:
            continue
        if inbound.get(page.slug, 0) == 0:
            result.warnings.append(
                f"{page.rel}: orphan — no other page links [[{page.slug}]]"
            )

    return result


def render_index(pages: list[vault.Page]) -> str:
    """Deterministically render wiki/index.md from page summaries."""
    content_pages = pages

    by_type: dict[str, list[vault.Page]] = defaultdict(list)
    for p in content_pages:
        by_type[str(p.frontmatter.get("type", "concept"))].append(p)

    lines: list[str] = [
        GENERATED_HEADER,
        "<!-- Regenerate with: python scripts/gen_index.py -->",
        "",
        "# SNP Memory System — Wiki Index",
        "",
        # NOTE: no timestamp here on purpose — the index must be a pure
        # function of the pages so `--check` is idempotent across days
        # (R-6.5). Git history records when it changed.
        f"_{len(content_pages)} pages · generated by gen_index.py — "
        f"do not edit by hand._",
        "",
    ]

    # Known types first (in TYPE_ORDER), then any unexpected types sorted.
    seen = set(TYPE_ORDER)
    ordered_types = TYPE_ORDER + sorted(t for t in by_type if t not in seen)

    for t in ordered_types:
        group = by_type.get(t)
        if not group:
            continue
        lines.append(f"## {TYPE_HEADING.get(t, t.title())}")
        lines.append("")
        for p in sorted(
            group, key=lambda x: str(x.frontmatter.get("title", x.slug)).lower()
        ):
            title = p.frontmatter.get("title", p.slug)
            summary = str(p.frontmatter.get("summary", "")).strip()
            href = p.path.relative_to(WIKI_DIR).as_posix()
            lines.append(f"- [{title}]({href}) — {summary}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _atomic_write_index(content: str) -> None:
    """Durably replace the generated index without exposing partial bytes."""
    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            prefix=f".{INDEX_PATH.name}.",
            suffix=".tmp",
            dir=INDEX_PATH.parent,
            delete=False,
        ) as handle:
            temporary = Path(handle.name)
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, INDEX_PATH)
        temporary = None
        directory_fd = os.open(INDEX_PATH.parent, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="lint + verify index.md is current; write nothing",
    )
    ap.add_argument(
        "--stdout",
        action="store_true",
        help="print the rendered index to stdout; write nothing "
        "(dry-run / CI / restricted-fs use)",
    )
    args = ap.parse_args()

    try:
        pages = vault.load_pages(WIKI_DIR)
    except ValueError as e:
        print(f"LINT ERROR: {e}")
        return 2

    lint = collect_lint(pages)
    for err in lint.errors:
        print(f"LINT ERROR: {err}")
    for w in lint.warnings:
        print(f"LINT WARN:  {w}")

    new_index = render_index(pages)
    current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
    index_current = current == new_index

    if args.stdout:
        # Lint still runs (printed above); emit content for external write.
        sys.stdout.write(new_index)
        return 0 if lint.ok else 1

    if args.check:
        if not index_current:
            print(
                "INDEX STALE: wiki/index.md is out of date — "
                "run `python scripts/gen_index.py` to regenerate."
            )
        status = "PASS" if (lint.ok and index_current) else "FAIL"
        print(
            f"\n{len(pages)} pages · {len(lint.errors)} errors · "
            f"{len(lint.warnings)} warnings · index "
            f"{'current' if index_current else 'STALE'} — {status}"
        )
        return 0 if (lint.ok and index_current) else 1

    # Write mode: refuse to regenerate the index if lint has hard errors —
    # a broken vault should be fixed before its index is stamped as good.
    if not lint.ok:
        print(
            f"\n{len(lint.errors)} lint error(s) — index NOT regenerated. "
            f"Fix errors first."
        )
        return 1

    if index_current:
        print(
            f"\nwiki/index.md already current ({len(pages)} pages). "
            f"{len(lint.warnings)} warning(s)."
        )
    else:
        try:
            _atomic_write_index(new_index)
            print(
                f"\nwiki/index.md regenerated ({len(pages)} pages). "
                f"{len(lint.warnings)} warning(s)."
            )
        except OSError as e:
            print(f"\nERROR: could not write {INDEX_PATH} ({e})")
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
