#!/usr/bin/env python3
"""Propose a multi-article decomposition from a source's own structure.

Bitwise-reproducible model output is not achievable, so anything that must be
stable across runs cannot be regenerated by a model on each run. A document
that numbers its own sections already carries the decomposition; extracting it
is a pure function of the bytes, which makes the skeleton stable by
construction rather than by hope.

There is no model call in this module. The output is a JSON plan meant to be
read and edited by a human before `compile_plan.py` acts on it: which sections
deserve a page, and where two should merge, is a judgement call this file
deliberately does not make.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from scout import vault  # noqa: E402
from scout.parsers import ParsedDocument, ParserError, parse_file  # noqa: E402

#: A numbered heading on its own line: "3.6.1  Medical Applications".
_HEADING_RE = re.compile(
    r"^[ \t]*(\d{1,2}(?:\.\d{1,2}){0,2})\.?[ \t]+([A-Z][A-Za-z0-9 ,\-/&()']{3,70})[ \t]*$"
)
#: Running headers repeat the journal line on every page; never a section.
_RUNNING_HEADER_RE = re.compile(r"^\s*\w+\s+\d{4},\s*\d+", re.IGNORECASE)
MAX_TITLE_CHARS = 200
DEFAULT_CATEGORY = "concept"


class PlanArticlesError(RuntimeError):
    """Raised when a decomposition cannot be proposed."""


@dataclass(frozen=True, slots=True)
class ProposedArticle:
    """One candidate wiki page, derived from one source heading."""

    section: str
    title: str
    loc: str
    slug: str
    category: str
    department: str


def slugify(title: str) -> str:
    """The page slug `compile_note` would derive from this title."""
    slug = re.sub(r"[^a-z0-9_-]+", "-", title.lower().strip()).strip("-")
    if not slug:
        raise PlanArticlesError(f"Title produces no safe slug: {title!r}")
    return slug


def extract_headings(document: ParsedDocument) -> list[tuple[str, str, str]]:
    """`(section, title, loc)` per heading, first occurrence wins, in page order.

    Papers re-emit headings in the table of contents and in running headers, so
    a naive scan double-counts. Keeping the first occurrence keeps the body
    heading when the ToC precedes it only if the ToC line is filtered — which is
    why headings whose text repeats are collapsed on the section number.
    """
    seen: dict[str, tuple[str, str, str]] = {}
    for section in document.sections:
        for line in section.text.splitlines():
            if _RUNNING_HEADER_RE.match(line):
                continue
            match = _HEADING_RE.match(line)
            if match is None:
                continue
            number, title = match.group(1), match.group(2).strip()
            if number in seen:
                continue
            seen[number] = (number, title, section.loc)
    return sorted(seen.values(), key=lambda item: _sort_key(item[0]))


def _sort_key(number: str) -> tuple[int, ...]:
    return tuple(int(part) for part in number.split("."))


def propose_articles(
    document: ParsedDocument,
    *,
    department: str,
    category: str = DEFAULT_CATEGORY,
    max_depth: int = 2,
) -> list[ProposedArticle]:
    """Candidate articles from the document's own numbered headings."""
    if department not in vault.VALID_DEPARTMENTS:
        raise PlanArticlesError(f"Invalid department: {department}")
    if category not in vault.VALID_TYPES:
        raise PlanArticlesError(f"Invalid category: {category}")
    if max_depth < 1:
        raise PlanArticlesError("max_depth must be at least 1")

    articles: list[ProposedArticle] = []
    used: set[str] = set()
    for number, title, loc in extract_headings(document):
        if len(number.split(".")) > max_depth:
            continue
        if len(title) > MAX_TITLE_CHARS:
            continue
        slug = slugify(title)
        if slug in used:
            continue
        used.add(slug)
        articles.append(
            ProposedArticle(
                section=number,
                title=title,
                loc=loc,
                slug=slug,
                category=category,
                department=department,
            )
        )
    if not articles:
        raise PlanArticlesError(
            "No numbered headings found. This source needs a hand-written plan: "
            "the decomposition cannot be derived from its structure."
        )
    return articles


def render_plan(source_path: str, articles: list[ProposedArticle]) -> str:
    """The plan file, stable byte-for-byte for a given source."""
    payload = {
        "source": source_path,
        "articles": [asdict(article) for article in articles],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--path", required=True, help="relative path beneath raw/")
    parser.add_argument("--dept", "--department", dest="department", required=True)
    parser.add_argument("--category", default=DEFAULT_CATEGORY)
    parser.add_argument("--max-depth", type=int, default=2)
    parser.add_argument("--out", default=None, help="plan file to write")
    args = parser.parse_args(argv)

    supplied = Path(args.path)
    resolved = (REPO_ROOT / supplied).resolve(strict=False)
    try:
        resolved.relative_to((REPO_ROOT / "raw").resolve(strict=False))
    except ValueError:
        print("ERROR: source must resolve beneath raw/", file=sys.stderr)
        return 2
    try:
        document = parse_file(resolved, REPO_ROOT)
        articles = propose_articles(
            document,
            department=args.department,
            category=args.category,
            max_depth=args.max_depth,
        )
    except (OSError, ParserError, PlanArticlesError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    rendered = render_plan(supplied.as_posix(), articles)
    if args.out:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(rendered, encoding="utf-8")
        print(f"Wrote {len(articles)} proposed article(s) to {out}", file=sys.stderr)
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
